version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "next-sanity"
        versions: ["> 0.0.0"] # Ignored due to peer dependency constraints
