import { Track } from "@prisma/client";
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const dayOrder = 12;
  const track = Track.DEVELOPMENT_ECONOMICS;
  console.log(`Starting update for Day \${dayOrder} (\${track})...`);

  // 1. UPDATE OR CREATE LESSON
  let lesson = await prisma.lesson.findUnique({
    where: {
      track_dayOrder: {
        track: track,
        dayOrder: dayOrder
      }
    }
  });

  const lessonData = {
    title: 'Why Innovation Creates Long-Term Growth',
    tag: track,
    timeEstimate: 5,
    track: track,
    dayOrder: dayOrder,
    conceptText: `In 1987, a 56-year-old engineer named Morris Chang raised 220 million dollars to build a chip factory in Taiwan that would design nothing at all. It would only manufacture chips other companies had designed — a business model the semiconductor industry considered a leftover, secondary market at best. That company, TSMC, now manufactures close to 90% of the world's most advanced logic chips.

The Solow growth model treats technology as a residual — something that shows up in the data as unexplained extra output, arriving from outside the model rather than being generated by any choice within it. Economist Paul Romer, whose work eventually earned a Nobel Memorial Prize in 2018, argued this missed the actual engine of long-run growth. Ideas, Romer pointed out, behave differently from capital or labor: one factory can only be used in one place at a time, but one idea — a manufacturing process, a chip design, a business model — can be used everywhere at once without ever being used up. Endogenous growth theory treats innovation not as a mysterious external gift but as something an economy can deliberately produce, through research, education, and the right incentives to keep producing more of it.

*An idea doesn't run out when you use it. It runs out when you stop having them.*

Taiwan's semiconductor industry is one of the cleanest illustrations available of what happens when a country builds its growth around exactly that insight, rather than around capital accumulation alone. The article ahead follows one company's business model into a near-monopoly on the chips the entire modern economy now runs on.`,
    conceptSummary: `Endogenous growth theory, associated with economist Paul Romer's 2018 Nobel-winning work, argues that ideas — unlike capital or labor — can be used everywhere at once without being used up, making innovation something an economy can deliberately generate rather than simply receive as an unexplained external gift, as the Solow model's residual implies.`,
    conceptTakeaways: [
      "Endogenous growth theory, linked to economist Paul Romer's 2018 Nobel-winning work, treats ideas as reusable without depletion, unlike capital or labor, making innovation something an economy can deliberately generate."
    ],
    articleTitle: 'The Factory That Only Makes Other People\'s Ideas',
    articleText: `**How did a secondary market idea transform the semiconductor industry?**
Before 1987, semiconductor companies designed and manufactured their own chips, a model requiring both cutting-edge engineering talent and billions of dollars in fabrication plants. Morris Chang, a semiconductor veteran, proposed something the industry hadn't organized itself around before: a "pure-play foundry" that would manufacture chips exclusively for other companies' designs, never competing with its own customers by selling a branded product. Taiwan's government supplied roughly 48% of TSMC's initial capital, the Dutch electronics firm Philips supplied about 28% along with crucial manufacturing technology, and the rest came from Taiwanese private investors.

**Why does a "fabless" business model make an idea more powerful?**
The insight wasn't really about factories at all. It was about separating an idea — how to design a chip — from the physical capital required to manufacture it, and letting the first spread as widely as demand would allow while charging for access to the second. Under Romer's framework, this is precisely what makes ideas different from ordinary capital: a "fabless" chip designer anywhere in the world could now access TSMC's accumulated manufacturing knowledge simply by placing an order without ever building a single factory.

**Does a factory's knowledge get depleted when multiple competitors use it?**
TSMC's own know-how wasn't diminished by serving a second customer, or a two-hundredth. If anything, each new customer's demanding requirements sharpened TSMC's own manufacturing process further, generating more ideas that then applied to every other customer already in line. An idea doesn't run out when you use it; it runs out when you stop having them, which is exactly why this knowledge compounded rather than depleted with use.

**Why would a company double its capital expenditure during a global financial crisis?**
By 2005, TSMC had captured half of the global semiconductor foundry market it had essentially invented. Rather than coast on that lead, the company kept reinvesting aggressively in research: even through the depths of the 2008 financial crisis, TSMC's leadership pushed capital expenditure from roughly 12 billion dollars cumulatively between 2005 and 2009 to around 40 billion dollars between 2010 and 2014. They bet that smartphones would reward whoever moved first on next-generation manufacturing processes, drawing in more demanding customers.

**How can serving one demanding customer benefit an entire industry?**
The relationship with Apple illustrates the compounding effect especially clearly. Once Apple became TSMC's largest customer, its exacting design requirements pushed TSMC's manufacturing precision to new levels — precision that then became available, at no extra cost of rediscovery, to every other company placing an order afterward. By 2023, TSMC's revenue reached 69.3 billion dollars, with more than 90% of the world's most advanced sub-7-nanometer chip production running through its factories alone.

**Why is an accumulated stock of know-how better than raw natural resources?**
None of this came from simply pouring in more capital, the way Japan's postwar factories or Korea's steel mills did. Taiwan had comparatively little of the raw natural-resource advantage Argentina once had, and a domestic market far too small to absorb the volume TSMC would eventually produce. What Taiwan built instead was an accumulating stock of manufacturing know-how that got more valuable, not less, every time someone else used it — the exact mechanism endogenous growth theory identifies as capable of generating growth that doesn't taper off the way capital accumulation alone eventually does.`,
    articleSummary: `Morris Chang's 1987 decision to found TSMC as a "pure-play foundry" separated chip design from chip manufacturing, letting the company's accumulated know-how serve an unlimited number of customers without being depleted. By 2023, TSMC held over 50% of the global foundry market and produced more than 90% of the world's most advanced chips — growth driven by accumulating, spreading ideas rather than capital investment alone.`,
    articleTakeaways: [
      "TSMC, founded in 1987 by Morris Chang with roughly 48% of its capital from Taiwan's government and 28% from Philips, pioneered the \"pure-play foundry\" model of manufacturing chips designed entirely by other companies.",
      "By 2005, TSMC held half of the global semiconductor foundry market; by 2023, its share exceeded 50%, with revenue reaching 69.3 billion dollars.",
      "TSMC now manufactures more than 90% of the world's most advanced (sub-7-nanometer) chips, reflecting an accumulated manufacturing knowledge base that grows more valuable with each additional customer rather than being depleted.",
      "Unlike capital accumulation, which runs into diminishing returns, accumulated know-how and innovation can generate growth that doesn't taper off in the same way, since ideas can be reused without being used up."
    ]
  };

  if (lesson) {
    lesson = await prisma.lesson.update({
      where: { id: lesson.id },
      data: lessonData
    });
    console.log(`Successfully updated Lesson for Day \${dayOrder}: \${lesson.title}`);
  } else {
    lesson = await prisma.lesson.create({
      data: lessonData
    });
    console.log(`Successfully created Lesson for Day \${dayOrder}: \${lesson.title}`);
  }

  // 2. UPDATE OR CREATE QUIZ
  let quiz = await prisma.quiz.findUnique({
    where: {
      track_dayOrder: {
        track: track,
        dayOrder: dayOrder
      }
    }
  });

  if (!quiz) {
    console.log(`Quiz for Day \${dayOrder} not found! Creating...`);
    quiz = await prisma.quiz.create({
      data: {
        track: track,
        dayOrder: dayOrder,
        title: "Quiz",
        tag: track,
        timeEstimate: 5
      }
    });
  }

  if (quiz) {
    // Delete existing questions
    await prisma.quizQuestion.deleteMany({
      where: { quizId: quiz.id }
    });

    const questions = [
      {
        questionText: "According to endogenous growth theory, how do ideas differ from capital or labor as sources of growth?",
        options: [
          "Ideas can only be used in one place at a time, just like capital",
          "Ideas can be used in multiple places simultaneously without being used up",
          "Ideas have no connection to economic growth",
          "Ideas depreciate faster than physical capital"
        ],
        correctAnswer: "Ideas can be used in multiple places simultaneously without being used up",
        explanation: "- a) Wrong — this describes physical capital's limitation, which the lesson explicitly contrasts with ideas.\\n- c) Wrong — the lesson positions ideas as the central driver of long-run growth in this framework.\\n- d) Wrong — the lesson describes ideas as not being \"used up\" at all, unlike physical capital, which does wear out."
      },
      {
        questionText: "What business model did Morris Chang introduce when founding TSMC in 1987?",
        options: [
          "A company that both designs and manufactures its own branded chips",
          "A \"pure-play foundry\" that manufactures chips designed exclusively by other companies",
          "A company focused solely on importing chips from other countries",
          "A retail chain selling consumer electronics"
        ],
        correctAnswer: "A \"pure-play foundry\" that manufactures chips designed exclusively by other companies",
        explanation: "- a) Wrong — this describes the traditional model TSMC's founding explicitly departed from.\\n- c) Wrong — TSMC is described as a manufacturer, not an importer or reseller.\\n- d) Wrong — TSMC is a manufacturing company serving other chip designers, not a consumer retail business."
      },
      {
        questionText: "According to the lesson, how was TSMC's initial capital funded?",
        options: [
          "Entirely by private American investors",
          "Roughly 48% by Taiwan's government, about 28% by Philips, and the remainder by Taiwanese private investors",
          "Entirely by TSMC's own prior profits",
          "By a loan from a single international bank"
        ],
        correctAnswer: "Roughly 48% by Taiwan's government, about 28% by Philips, and the remainder by Taiwanese private investors",
        explanation: "- a) Wrong — the lesson specifically attributes the largest funding share to Taiwan's government, not American investors.\\n- c) Wrong — TSMC had no prior profits at its 1987 founding, since it was a new company.\\n- d) Wrong — the lesson describes a mix of government, foreign corporate, and private investors, not a single bank loan."
      },
      {
        questionText: "Why doesn't serving additional customers deplete TSMC's manufacturing know-how, according to the lesson?",
        options: [
          "Because manufacturing know-how behaves like an idea, which can be applied repeatedly without being used up",
          "Because TSMC actually loses knowledge with each new customer",
          "Because TSMC limits itself to exactly one customer at a time",
          "Because manufacturing know-how has no relationship to the number of customers served"
        ],
        correctAnswer: "Because manufacturing know-how behaves like an idea, which can be applied repeatedly without being used up",
        explanation: "- b) Wrong — this reverses the lesson's point; know-how compounds rather than depletes with more customers.\\n- c) Wrong — the lesson describes TSMC serving many different fabless companies simultaneously.\\n- d) Wrong — the lesson directly connects growing customer demands to sharpening TSMC's manufacturing process further."
      },
      {
        questionText: "What happened to TSMC's cumulative capital expenditure between the 2005-2009 period and the 2010-2014 period?",
        options: [
          "It fell from about 40 billion dollars to about 12 billion dollars",
          "It rose from about 12 billion dollars to about 40 billion dollars",
          "It remained completely unchanged",
          "It dropped to zero during the financial crisis"
        ],
        correctAnswer: "It rose from about 12 billion dollars to about 40 billion dollars",
        explanation: "- a) Wrong — this reverses the actual direction of the increase described in the lesson.\\n- c) Wrong — the lesson describes a substantial increase, not stability.\\n- d) Wrong — the lesson describes increased, not eliminated, investment during this period."
      },
      {
        questionText: "By 2023, what share of the world's most advanced (sub-7-nanometer) chip production did TSMC account for, according to the lesson?",
        options: [
          "Less than 10%",
          "About 25%",
          "More than 90%",
          "Exactly 50%, with no more and no less"
        ],
        correctAnswer: "More than 90%",
        explanation: "- a) Wrong — this drastically understates TSMC's described dominance in advanced chip production.\\n- b) Wrong — this also understates the figure given in the lesson.\\n- d) Wrong — 50% is closer to TSMC's overall foundry market share, not its specific share of advanced chip production."
      },
      {
        questionText: "A small country with limited natural resources and a small domestic market is deciding how to build long-term economic growth. Based on the lesson's argument about Taiwan, what strategy is most directly supported?",
        options: [
          "Focus exclusively on natural resource extraction, since that's the only reliable growth source",
          "Invest in building specialized, reusable know-how or technology that can serve customers well beyond the domestic market, similar to TSMC's approach",
          "Avoid all foreign investment and partnerships entirely",
          "Rely solely on population growth to drive economic expansion"
        ],
        correctAnswer: "Invest in building specialized, reusable know-how or technology that can serve customers well beyond the domestic market, similar to TSMC's approach",
        explanation: "- a) Wrong — the lesson explicitly notes Taiwan lacked significant natural resource advantages, yet still achieved substantial growth through specialized knowledge instead.\\n- c) Wrong — the lesson describes TSMC's founding as directly reliant on foreign capital and technology from Philips.\\n- d) Wrong — the lesson attributes Taiwan's growth to accumulated know-how, not population expansion."
      },
      {
        questionText: "An entrepreneur is deciding whether to build a company that designs and manufactures its own product, or one that provides a specialized service other companies can use repeatedly. Based on the lesson's framework, what is the key advantage of the second model, if it resembles TSMC's approach?",
        options: [
          "It requires no capital investment of any kind",
          "The underlying expertise or process can be reused across many clients without being depleted, unlike a single physical product",
          "It guarantees higher short-term profit than any other business model",
          "It eliminates all competition permanently"
        ],
        correctAnswer: "The underlying expertise or process can be reused across many clients without being depleted, unlike a single physical product",
        explanation: "- a) Wrong — the lesson explicitly describes very large capital requirements for TSMC's foundry model.\\n- c) Wrong — the lesson doesn't claim this model guarantees higher short-term profits, only durable, expanding know-how.\\n- d) Wrong — the lesson doesn't claim this model eliminates competition; it describes TSMC operating within a competitive foundry market it came to dominate."
      },
      {
        questionText: "Why does the lesson argue that Taiwan's semiconductor growth doesn't fit a purely Solow-style capital-accumulation story?",
        options: [
          "Because Taiwan invested no capital in its semiconductor industry at all",
          "Because the growth is attributed to accumulating, reusable know-how that compounds with use, rather than physical capital alone, which runs into diminishing returns",
          "Because Taiwan has no domestic market of any kind",
          "Because Solow's model applies only to agricultural economies"
        ],
        correctAnswer: "Because the growth is attributed to accumulating, reusable know-how that compounds with use, rather than physical capital alone, which runs into diminishing returns",
        explanation: "- a) Wrong — the lesson describes substantial capital investment in TSMC, but frames the growth engine as knowledge, not capital alone.\\n- c) Wrong — the lesson notes Taiwan's domestic market was too small to absorb TSMC's output, not that it lacked one entirely.\\n- d) Wrong — the Solow model is applied broadly across the lessons in this course, not restricted to agricultural economies."
      },
      {
        questionText: "Based on this lesson and the earlier lesson on capital accumulation and diminishing returns, which of the following best explains why TSMC's growth might avoid the same slowdown pattern China's infrastructure investment experienced?",
        options: [
          "TSMC's growth relies on reusable, compounding know-how rather than physical capital alone, which is less subject to the same diminishing-returns pattern as repeated construction investment",
          "TSMC has never invested in any physical capital at all",
          "China's infrastructure investment and TSMC's manufacturing know-how are identical in every respect",
          "Diminishing returns apply equally and identically to all forms of investment, with no distinction between physical capital and ideas"
        ],
        correctAnswer: "TSMC's growth relies on reusable, compounding know-how rather than physical capital alone, which is less subject to the same diminishing-returns pattern as repeated construction investment",
        explanation: "- b) Wrong — the lesson explicitly describes massive capital expenditure by TSMC on fabrication plants.\\n- c) Wrong — the lesson draws a clear distinction between reusable ideas and physical capital like roads or buildings.\\n- d) Wrong — the lesson's entire argument rests on ideas behaving differently from physical capital regarding diminishing returns."
      }
    ];

    for (let i = 0; i < questions.length; i++) {
      await prisma.quizQuestion.create({
        data: {
          quizId: quiz.id,
          questionText: questions[i].questionText,
          options: questions[i].options,
          correctAnswer: questions[i].correctAnswer,
          explanation: questions[i].explanation,
          order: i + 1,
        }
      });
    }
    console.log(`Successfully updated \${questions.length} Quiz Questions for Day \${dayOrder}`);
  } else {
    console.log(`Quiz for Day \${dayOrder} failed to create or load!`);
  }
}

main()
  .catch(e => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });
